### ISSUE TITLE
Identifying Medical Diagnoses and Treatable Diseases by Image-Based Deep Learning

### ISSUE THREAD

**Issue by hasibzunair** [mlmed/cxr-dataset-list#1]
Data is available [here](https://data.mendeley.com/datasets/rscbjbr9sj/3), along with the [paper](https://www.cell.com/cell/fulltext/S0092-8674(18)30154-5).

The chest X-ray images are from children which are labelled as either normal or pneumonia (both bacterial and viral). A total of 5,856  patient data is used for training, 624 patient data for testing.

**Comment by ieee8023** [comment]
Can you make a pull request for it?

**Comment by hasibzunair** [comment]
Sure!
